### ISSUE TITLE
US1 - Issue 1 - Servicio de consulta de cursos para alumnos devuelve cursos inactivos

### ISSUE THREAD

**Issue by OsirisArguello** [dkux/quechua-core#1]
Pasos para reproducir:
1-Invocar al servicio de consulta de cursos para alumnos

Comportamiento esperado:
Devolver solo los cursos activos

Comportamiento actual:
Devuelve cursos, sin importar su estado.

**Comment by OsirisArguello** [comment]
Dani, acá capaz convendría que el servicio no devuelva todos los cursos sino solo los activos. Yo cambiaria la implementación para que reciba idMateria y que devuelva los cursos activos de esa materia.

**Comment by dkux** [comment]
Agregué un nuevo endpoint para obtener los cursos por materia: /materias/{materiaId}/cursos
