### ISSUE TITLE
US3 - Issue 2 - Servicio de consulta de curso del docente no devuelve horario

### ISSUE THREAD

**Issue by OsirisArguello** [dkux/quechua-core#2]
Pasos para reproducir:
1- Invocar al servicio de consulta de curso del docente con id de curso 1:
/public/cursos/1/inscripciones

Comportamiento esperado:
1-Devuelve los datos del curso con el horario

Comportamiento actual:
2-Devuelve horario null

**Comment by dkux** [comment]
Resuelto
