### ISSUE TITLE
US1 - Issue 3 - No devuelve las inscripciones en los cursos

### ISSUE THREAD

**Issue by OsirisArguello** [dkux/quechua-core#3]
Pasos para reproducir:
1-Invocar al servicio de consulta de cursos para alumnos

Comportamiento esperado:
Devolver las inscripciones actuales en el objeto curso

Comportamiento actual:
No devuelve las inscripciones actuales

**Comment by dkux** [comment]
Agregué en la respuesta la cantidad de vacantes disponibles. El campo se llama vacantesDisponinbles, te sirve?

**Comment by OsirisArguello** [comment]
Mmm no me sirve, necesito las inscripciones porque para mostrar o no el
botón de inscribir necesito saber si el tipo está inscripto o no en un
curso. Sino me vas a tener que hacer otro servicio para consultar si un
alumno está inscripto o no y lo veo más enquilombado.

**Comment by dkux** [comment]
Listo, le incluí las inscripciones, me parece un poco mucho mandar toda esa cantidad de datos, pero puede ser un provisorio por este sprint o por el fin de los tiempos
