### ISSUE TITLE
US3 - Issue 4 - Devolver la lista de inscriptos por orden alfabetico

### ISSUE THREAD

**Issue by OsirisArguello** [dkux/quechua-core#4]
Pasos para reproducir:
Invocar al servicio con la url /public/cursos/{cursoID}/inscripciones

Comportamiento Esperado:
Devuelve los inscriptos por orden alfabetico

Comportamiento Actual:
Devuelve los inscriptos fuera de orden

**Comment by dkux** [comment]
Done
